import { MigrationInterface, QueryRunner } from "typeorm";

export class  Create1739674217629 implements MigrationInterface {
    name = ' Create1739674217629'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."ARQUIVO_situacao_enum" AS ENUM('A', 'D', 'E', 'P', 'T')`);
        await queryRunner.query(`CREATE TABLE "ARQUIVO" ("USUARIO_CRIACAO" character varying(300) NOT NULL, "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "USUARIO_ATUALIZACAO" character varying(300) NOT NULL, "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "ID_ECM" character varying(80), "NOME" character varying(300) NOT NULL, "SITUACAO" "public"."ARQUIVO_situacao_enum" NOT NULL DEFAULT 'P', "NUMERO_BYTES" numeric(20), "DATA_HORA_TRANSMISSAO" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f172e98e7c6d049111c5997a16b" PRIMARY KEY ("ID")); COMMENT ON COLUMN "ARQUIVO"."USUARIO_CRIACAO" IS 'ID de autenticação do usuário de criação do registro'; COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_CRIACAO" IS 'Data e hora de criação do registro'; COMMENT ON COLUMN "ARQUIVO"."USUARIO_ATUALIZACAO" IS 'ID de autenticação do usuário de atualização do registro'; COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_ATUALIZACAO" IS 'Data e hora de atualização do registro'; COMMENT ON COLUMN "ARQUIVO"."ID" IS 'ID do arquivo (PK)'; COMMENT ON COLUMN "ARQUIVO"."ID_ECM" IS 'Identificador do arquivo no ECM'; COMMENT ON COLUMN "ARQUIVO"."NOME" IS 'Nome do arquivo'; COMMENT ON COLUMN "ARQUIVO"."SITUACAO" IS 'Situação de envio do arquivo no ECM'; COMMENT ON COLUMN "ARQUIVO"."NUMERO_BYTES" IS 'Tamanho do arquivo em bytes'; COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_TRANSMISSAO" IS 'Data e hora da transmissão do arquivo ao ECM'`);
        await queryRunner.query(`CREATE TABLE "ARQUIVO_CONTEUDO" ("USUARIO_CRIACAO" character varying(300) NOT NULL, "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "USUARIO_ATUALIZACAO" character varying(300) NOT NULL, "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "CONTEUDO" bytea NOT NULL, "ORGANIZACAO" character varying(100) NOT NULL, "SISTEMA" character varying(100) NOT NULL, "NOME" character varying(300) NOT NULL, "TIPO" character varying(50) NOT NULL, CONSTRAINT "PK_f226d20d74f9f82cc7ecb708377" PRIMARY KEY ("ID")); COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."USUARIO_CRIACAO" IS 'ID de autenticação do usuário de criação do registro'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."DATA_HORA_CRIACAO" IS 'Data e hora de criação do registro'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."USUARIO_ATUALIZACAO" IS 'ID de autenticação do usuário de atualização do registro'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."DATA_HORA_ATUALIZACAO" IS 'Data e hora de atualização do registro'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."ID" IS 'ID do conteúdo do arquivo (PK)'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."CONTEUDO" IS 'Conteúdo binário do arquivo'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."ORGANIZACAO" IS 'Nome da organização que o arquivo ficará vinculado'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."SISTEMA" IS 'Nome do sistema que enviou o arquivo'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."NOME" IS 'Nome do arquivo para o sistema cliente'; COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."TIPO" IS 'Tipo do arquivo para o sistema cliente'`);
        await queryRunner.query(`CREATE TABLE "SOLICITACAO" ("USUARIO_CRIACAO" character varying(300) NOT NULL, "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "USUARIO_ATUALIZACAO" character varying(300) NOT NULL, "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "ORGANIZACAO" character varying(100) NOT NULL, "SISTEMA" character varying(100) NOT NULL, "DATA_HORA_EXPIRACAO" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_48e49928ff43fdec699df67ebb1" PRIMARY KEY ("ID")); COMMENT ON COLUMN "SOLICITACAO"."USUARIO_CRIACAO" IS 'ID de autenticação do usuário de criação do registro'; COMMENT ON COLUMN "SOLICITACAO"."DATA_HORA_CRIACAO" IS 'Data e hora de criação do registro'; COMMENT ON COLUMN "SOLICITACAO"."USUARIO_ATUALIZACAO" IS 'ID de autenticação do usuário de atualização do registro'; COMMENT ON COLUMN "SOLICITACAO"."DATA_HORA_ATUALIZACAO" IS 'Data e hora de atualização do registro'; COMMENT ON COLUMN "SOLICITACAO"."ID" IS 'ID da solicitação (PK)'; COMMENT ON COLUMN "SOLICITACAO"."ORGANIZACAO" IS 'Nome da organização que a solicitação ficará vinculada'; COMMENT ON COLUMN "SOLICITACAO"."SISTEMA" IS 'Nome do sistema que solicitou o envio de arquivos'; COMMENT ON COLUMN "SOLICITACAO"."DATA_HORA_EXPIRACAO" IS 'Data e hora de expiração da solicitação'`);
        await queryRunner.query(`CREATE TABLE "SOLICITACAO_ARQUIVO" ("USUARIO_CRIACAO" character varying(300) NOT NULL, "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "USUARIO_ATUALIZACAO" character varying(300) NOT NULL, "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "NOME" character varying(300) NOT NULL, "TIPO" character varying(50) NOT NULL, CONSTRAINT "PK_95d3ca3531a4b3ab9a28334fe48" PRIMARY KEY ("ID")); COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."USUARIO_CRIACAO" IS 'ID de autenticação do usuário de criação do registro'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."DATA_HORA_CRIACAO" IS 'Data e hora de criação do registro'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."USUARIO_ATUALIZACAO" IS 'ID de autenticação do usuário de atualização do registro'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."DATA_HORA_ATUALIZACAO" IS 'Data e hora de atualização do registro'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."ID" IS 'ID da solicitação de arquivo (PK)'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."NOME" IS 'Nome do arquivo para o sistema cliente'; COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."TIPO" IS 'Tipo do arquivo para o sistema cliente'`);
        await queryRunner.query(`ALTER TABLE "ARQUIVO_CONTEUDO" ADD CONSTRAINT "FK_f226d20d74f9f82cc7ecb708377" FOREIGN KEY ("ID") REFERENCES "ARQUIVO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SOLICITACAO_ARQUIVO" ADD CONSTRAINT "FK_95d3ca3531a4b3ab9a28334fe48" FOREIGN KEY ("ID") REFERENCES "SOLICITACAO"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "SOLICITACAO_ARQUIVO" DROP CONSTRAINT "FK_95d3ca3531a4b3ab9a28334fe48"`);
        await queryRunner.query(`ALTER TABLE "ARQUIVO_CONTEUDO" DROP CONSTRAINT "FK_f226d20d74f9f82cc7ecb708377"`);
        await queryRunner.query(`DROP TABLE "SOLICITACAO_ARQUIVO"`);
        await queryRunner.query(`DROP TABLE "SOLICITACAO"`);
        await queryRunner.query(`DROP TABLE "ARQUIVO_CONTEUDO"`);
        await queryRunner.query(`DROP TABLE "ARQUIVO"`);
        await queryRunner.query(`DROP TYPE "public"."ARQUIVO_situacao_enum"`);
    }

}
