DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ARQUIVO_situacao_enum') THEN
        CREATE TYPE "public"."ARQUIVO_situacao_enum" AS ENUM('A', 'D', 'E', 'P', 'T');
    END IF;
END $$;

CREATE TABLE "ARQUIVO" (
  "ID" uuid PRIMARY KEY,
  "USUARIO_CRIACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "USUARIO_ATUALIZACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "ID_ECM" VARCHAR(80),
  "NOME" VARCHAR(300) NOT NULL,
  "SITUACAO" "public"."ARQUIVO_situacao_enum" NOT NULL DEFAULT 'P',
  "NUMERO_BYTES" NUMERIC(20),
  "DATA_HORA_TRANSMISSAO" TIMESTAMP WITH TIME ZONE
);

COMMENT ON COLUMN "ARQUIVO"."USUARIO_CRIACAO" IS 'ID de autenticação do usuário de criação do registro';
COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_CRIACAO" IS 'Data e hora de criação do registro';
COMMENT ON COLUMN "ARQUIVO"."USUARIO_ATUALIZACAO" IS 'ID de autenticação do usuário de atualização do registro';
COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_ATUALIZACAO" IS 'Data e hora de atualização do registro';
COMMENT ON COLUMN "ARQUIVO"."ID" IS 'ID do arquivo (PK)';
COMMENT ON COLUMN "ARQUIVO"."ID_ECM" IS 'Identificador do arquivo no ECM';
COMMENT ON COLUMN "ARQUIVO"."NOME" IS 'Nome do arquivo';
COMMENT ON COLUMN "ARQUIVO"."SITUACAO" IS 'Situação de envio do arquivo no ECM';
COMMENT ON COLUMN "ARQUIVO"."NUMERO_BYTES" IS 'Tamanho do arquivo em bytes';
COMMENT ON COLUMN "ARQUIVO"."DATA_HORA_TRANSMISSAO" IS 'Data e hora da transmissão do arquivo ao ECM';

CREATE TABLE "ARQUIVO_CONTEUDO" (
  "ID" uuid PRIMARY KEY,
  "USUARIO_CRIACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "USUARIO_ATUALIZACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "CONTEUDO" BYTEA NOT NULL,
  "ORGANIZACAO" VARCHAR(100) NOT NULL,
  "SISTEMA" VARCHAR(100) NOT NULL,
  "NOME" VARCHAR(300) NOT NULL,
  "TIPO" VARCHAR(50) NOT NULL,
  "ID_ARQUIVO" uuid, 
  CONSTRAINT "FK_ARQUIVO_CONTEUDO" FOREIGN KEY ("ID_ARQUIVO") REFERENCES "ARQUIVO"("ID")
);

COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."CONTEUDO" IS 'Conteúdo binário do arquivo';
COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."ORGANIZACAO" IS 'Nome da organização que o arquivo ficará vinculado';
COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."SISTEMA" IS 'Nome do sistema que enviou o arquivo';
COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."NOME" IS 'Nome do arquivo para o sistema cliente';
COMMENT ON COLUMN "ARQUIVO_CONTEUDO"."TIPO" IS 'Tipo do arquivo para o sistema cliente';

CREATE TABLE "SOLICITACAO" (
  "ID" uuid PRIMARY KEY,
  "USUARIO_CRIACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "USUARIO_ATUALIZACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "ORGANIZACAO" VARCHAR(100) NOT NULL,
  "SISTEMA" VARCHAR(100) NOT NULL,
  "DATA_HORA_EXPIRACAO" TIMESTAMP WITH TIME ZONE
);

COMMENT ON COLUMN "SOLICITACAO"."ORGANIZACAO" IS 'Nome da organização que a solicitação ficará vinculada';
COMMENT ON COLUMN "SOLICITACAO"."SISTEMA" IS 'Nome do sistema que solicitou o envio de arquivos';
COMMENT ON COLUMN "SOLICITACAO"."DATA_HORA_EXPIRACAO" IS 'Data e hora de expiração da solicitação';

CREATE TABLE "SOLICITACAO_ARQUIVO" (
  "ID" uuid PRIMARY KEY,
  "USUARIO_CRIACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_CRIACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "USUARIO_ATUALIZACAO" VARCHAR(300) NOT NULL,
  "DATA_HORA_ATUALIZACAO" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "NOME" VARCHAR(300) NOT NULL,
  "TIPO" VARCHAR(50) NOT NULL,
  "ID_SOLICITACAO" uuid,
  CONSTRAINT "FK_SOLICITACAO_ARQUIVO" FOREIGN KEY ("ID_SOLICITACAO") REFERENCES "SOLICITACAO"("ID")
);

COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."NOME" IS 'Nome do arquivo para o sistema cliente';
COMMENT ON COLUMN "SOLICITACAO_ARQUIVO"."TIPO" IS 'Tipo do arquivo para o sistema cliente';
